inherit_from: .rubocop_todo.yml

require: rubocop-rspec
AllCops:
  Exclude:
    - Guardfile
    - db/schema.rb
    - lib/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*
    - node_modules/**/*
Style/Documentation:
  Enabled: false
Lint/Debugger:
  AutoCorrect: false
Layout/LineLength:
  Max: 120
Naming/MemoizedInstanceVariableName:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Metrics/MethodLength:
  Exclude:
    - db/**/*
Metrics/AbcSize:
  Exclude:
    - db/**/*
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*
RSpec/NestedGroups:
  Max: 4
